// nuxt-app/app/components/RecordingModal.vue
<!-- app/components/RecordingModal.vue -->

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'

type RecognizerType = 'fingerprint' | 'humming'

const props = defineProps<{
  audioStream: MediaStream | null
  selectedRecognizer: RecognizerType
}>()

const emit = defineEmits<{
  (e: 'stop'): void
  (e: 'close'): void
  (e: 'save', audioBlob: Blob): void
}>()

const canvasRef = ref<HTMLCanvasElement | null>(null)

let audioContext: AudioContext | null = null
let mediaStreamSource: MediaStreamAudioSourceNode | null = null
let analyser: AnalyserNode | null = null

const mediaRecorder = ref<MediaRecorder | null>(null)
const audioChunks = ref<BlobPart[]>([])

let animationFrameId: number | null = null
let intervalId: ReturnType<typeof setInterval> | null = null

const currentDate = ref('')
const formattedRecordingTime = ref('00:00')
const recordingTime = ref(0)
const isPaused = ref(false)

// ---- util
const formatTime = (time: number): string => {
  const minutes = Math.floor(time / 60).toString().padStart(2, '0')
  const seconds = Math.floor(time % 60).toString().padStart(2, '0')
  return `${minutes}:${seconds}`
}

const startTimer = () => {
  if (intervalId !== null) {
    clearInterval(intervalId)
    intervalId = null
  }
  intervalId = setInterval(() => {
    recordingTime.value++
    formattedRecordingTime.value = formatTime(recordingTime.value)
  }, 1000)
}

const stopTimer = () => {
  if (intervalId !== null) {
    clearInterval(intervalId)
    intervalId = null
  }
}

const stopDraw = () => {
  if (animationFrameId !== null) {
    cancelAnimationFrame(animationFrameId)
    animationFrameId = null
  }
}

const draw = () => {
  if (!analyser || !canvasRef.value) return

  const canvas = canvasRef.value
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const bufferLength = analyser.frequencyBinCount
  const dataArray = new Uint8Array(bufferLength)

  analyser.getByteTimeDomainData(dataArray)

  ctx.fillStyle = '#222'
  ctx.fillRect(0, 0, canvas.width, canvas.height)

  ctx.lineWidth = 2
  ctx.strokeStyle = 'white'
  ctx.beginPath()

  const sliceWidth = canvas.width / bufferLength
  let x = 0

  for (let i = 0; i < bufferLength; i++) {
    const value = dataArray[i] ?? 128
    const v = value / 128.0
    const y = (v * canvas.height) / 2

    if (i === 0) ctx.moveTo(x, y)
    else ctx.lineTo(x, y)
    x += sliceWidth
  }

  ctx.lineTo(canvas.width, canvas.height / 2)
  ctx.stroke()

  animationFrameId = requestAnimationFrame(draw)
}

// 브라우저가 지원하는 mimeType 선택
const pickMimeType = (): string | undefined => {
  const candidates = [
    'audio/webm;codecs=opus',
    'audio/webm',
    'audio/ogg;codecs=opus',
    'audio/ogg',
  ]
  for (const t of candidates) {
    if (typeof MediaRecorder !== 'undefined' && MediaRecorder.isTypeSupported(t)) return t
  }
  return undefined
}

const setup = async (stream: MediaStream) => {
  // 날짜 표시
  const now = new Date()
  currentDate.value = now.toLocaleString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric',
  })

  // timer reset/start
  recordingTime.value = 0
  formattedRecordingTime.value = '00:00'
  startTimer()

  // AudioContext + analyser
  audioContext = new AudioContext()
  analyser = audioContext.createAnalyser()
  analyser.fftSize = 2048

  mediaStreamSource = audioContext.createMediaStreamSource(stream)
  mediaStreamSource.connect(analyser)

  // canvas size
  const canvas = canvasRef.value
  if (canvas) {
    canvas.width = canvas.offsetWidth || 300
    canvas.height = 150
  }

  // MediaRecorder
  audioChunks.value = []
  const mimeType = pickMimeType()

  mediaRecorder.value = new MediaRecorder(stream, mimeType ? { mimeType } : undefined)

  mediaRecorder.value.ondataavailable = (event: BlobEvent) => {
    if (event.data && event.data.size > 0) {
      audioChunks.value.push(event.data)
    }
  }

  mediaRecorder.value.start()
  draw()
}

const teardown = async () => {
  stopDraw()
  stopTimer()

  try {
    if (mediaStreamSource) {
      mediaStreamSource.disconnect()
      mediaStreamSource = null
    }
    analyser = null

    if (audioContext) {
      await audioContext.close()
      audioContext = null
    }
  } catch {
    // ignore close errors
  }

  // MediaRecorder 정리 (스트림 stop은 부모에서 함)
  if (mediaRecorder.value) {
    // recording / paused 상태면 안전하게 stop
    if (mediaRecorder.value.state !== 'inactive') {
      try {
        mediaRecorder.value.stop()
      } catch {
        // ignore
      }
    }
    mediaRecorder.value.ondataavailable = null
    mediaRecorder.value.onstop = null
    mediaRecorder.value = null
  }
}

// ---- actions
const stopRecording = () => {
  stopTimer()
  stopDraw()

  const mr = mediaRecorder.value
  if (mr && mr.state !== 'inactive') {
    // stop 완료 후 blob 만들기
    mr.onstop = () => {
      const blob = new Blob(audioChunks.value, {
        type: mr.mimeType || 'audio/webm',
      })
      emit('save', blob)
      emit('stop')
      emit('close')
    }
    mr.stop()
    return
  }

  emit('stop')
  emit('close')
}

const togglePause = () => {
  const mr = mediaRecorder.value
  if (!mr || mr.state === 'inactive') return

  isPaused.value = !isPaused.value

  if (isPaused.value) {
    // pause
    stopTimer()
    stopDraw()
    try {
      mr.pause()
    } catch {}
  } else {
    // resume
    startTimer()
    try {
      mr.resume()
    } catch {}
    draw()
  }
}

// ---- lifecycle
onMounted(async () => {
  // v-if 조건이 있지만, 타입상 null 가능하니 방어
  if (!props.audioStream) {
    console.error('audioStream이 존재하지 않습니다.')
    emit('stop')
    emit('close')
    return
  }

  try {
    await setup(props.audioStream)
  } catch (e) {
    console.error('오디오 시각화/녹음 초기화 오류:', e)
    emit('stop')
    emit('close')
  }
})

// 부모가 stream을 바꿔끼우는 경우 대비(선택)
watch(
  () => props.audioStream,
  async (newStream, oldStream) => {
    if (newStream === oldStream) return
    await teardown()
    if (newStream) {
      await setup(newStream)
    }
  }
)

onBeforeUnmount(async () => {
  await teardown()
})
</script>

<template>
  <div class="modal">
    <div class="modal-content">
      <div class="top-info">
        <h2>녹음 중</h2>
        <p class="date">{{ currentDate }}</p>
      </div>

      <canvas ref="canvasRef" class="waveform"></canvas>

      <p class="recording-time">{{ formattedRecordingTime }}</p>

      <div class="controls">
        <button class="control-button pause" @click="togglePause">
          <i :class="isPaused ? 'fas fa-play' : 'fas fa-pause'"></i>
        </button>

        <button class="control-button stop" @click="stopRecording">
          <i class="fas fa-stop"></i>
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.modal {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.8); /* 배경색 변경 */
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000; /* 다른 요소보다 항상 위에 표시 */
}

.modal-content {
  background-color: #fff; /* 밝은 배경색 */
  padding: 20px;
  border-radius: 15px; /* 둥근 모서리 */
  min-width: 350px; /* 적절한 최소 너비 */
  display: flex;
  flex-direction: column;
  align-items: center;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* 그림자 효과 */
}

/* 상단 정보 영역 스타일 */
.top-info {
  text-align: center;
  margin-bottom: 20px;
}

.top-info h2 {
  color: #333; /* 제목 색상 */
  font-size: 1.8em; /* 제목 크기 */
  margin-bottom: 5px;
}

.top-info .date {
  color: #777; /* 날짜 색상 */
  font-size: 0.9em; /* 날짜 크기 */
}

/* 파형 표시 영역 스타일 */
.waveform {
  width: 100%;
  height: 150px;
  background-color: #eee; /* 파형 배경색 */
  border-radius: 8px;
  margin-bottom: 20px;
}

/* 녹음 시간 표시 스타일 */
.recording-time {
  color: #555; /* 시간 색상 */
  font-size: 2.2em; /* 시간 크기 */
  margin-bottom: 30px;
}

/* 컨트롤 버튼 영역 스타일 */
.controls {
  display: flex;
  justify-content: space-around;
  width: 100%;
}

.control-button {
  width: 70px;
  height: 70px;
  border-radius: 50%;
  border: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 28px; /* 아이콘 크기 */
  color: white;
  transition: transform 0.2s ease-in-out; /* 클릭 효과 */
}

.control-button:hover {
  transform: scale(1.1); /* 호버 시 약간 확대 */
}

/* 일시정지 버튼 스타일 */
.control-button.pause {
  background-color: #1acc22; /* 초록색 */
}

/* 정지 버튼 스타일 */
.control-button.stop {
  background-color: #dc3545; /* 빨간색 */
}

/* 아이콘 스타일 */
.control-button i {
  pointer-events: none;
}
</style>

// frontend/src/features/search/RecordingModal.tsx
import { useEffect, useRef, useState } from 'react'
import { motion } from 'motion/react'
import { Pause, Play, Square } from 'lucide-react'

interface Props {
  stream: MediaStream
  onSave: (blob: Blob) => void
  onStop: () => void
}

function formatTime(t: number): string {
  const m = Math.floor(t / 60).toString().padStart(2, '0')
  const s = Math.floor(t % 60).toString().padStart(2, '0')
  return `${m}:${s}`
}

function pickMimeType(): string | undefined {
  const candidates = ['audio/webm;codecs=opus', 'audio/webm', 'audio/ogg;codecs=opus', 'audio/ogg', 'audio/mp4']
  for (const t of candidates) {
    if (typeof MediaRecorder !== 'undefined' && MediaRecorder.isTypeSupported(t)) return t
  }
  return undefined
}

export function RecordingModal({ stream, onSave, onStop }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const recorderRef = useRef<MediaRecorder | null>(null)
  const stopFnRef = useRef<() => void>(() => {})
  const rafRef = useRef<number | null>(null)
  const pausedRef = useRef(false)

  const [seconds, setSeconds] = useState(0)
  const [paused, setPaused] = useState(false)

  useEffect(() => {
    // ⚠️ chunks는 이 이펙트 실행(=이 녹음기)의 클로저가 독립 소유한다.
    // StrictMode 이중 실행이나 재마운트에서도 다른 녹음기 데이터와 섞이지 않는다.
    const chunks: BlobPart[] = []

    const audioCtx = new AudioContext()
    const analyser = audioCtx.createAnalyser()
    analyser.fftSize = 2048
    const source = audioCtx.createMediaStreamSource(stream)
    source.connect(analyser)

    const mimeType = pickMimeType()
    const recorder = new MediaRecorder(stream, mimeType ? { mimeType } : undefined)
    recorder.ondataavailable = (e) => {
      if (e.data.size > 0) chunks.push(e.data)
    }
    recorder.start(200) // timeslice: 녹음 중에도 200ms마다 데이터 수집
    recorderRef.current = recorder

    // 정지 버튼 → 이 녹음기의 chunks로 blob 생성 후 저장
    stopFnRef.current = () => {
      // 종료 애니메이션과 경쟁하지 않도록 캔버스 draw 루프를 즉시 멈춘다.
      if (rafRef.current !== null) {
        cancelAnimationFrame(rafRef.current)
        rafRef.current = null
      }
      if (recorder.state !== 'inactive') {
        recorder.onstop = () => {
          const blob = new Blob(chunks, { type: recorder.mimeType || mimeType || 'audio/webm' })
          onSave(blob)
          onStop()
        }
        recorder.stop()
      } else {
        onStop()
      }
    }

    const canvas = canvasRef.current
    if (canvas) {
      canvas.width = canvas.offsetWidth || 320
      canvas.height = 140
    }

    const draw = () => {
      rafRef.current = requestAnimationFrame(draw)
      const c = canvasRef.current
      const ctx = c?.getContext('2d')
      if (!c || !ctx) return
      const buffer = new Uint8Array(analyser.frequencyBinCount)
      analyser.getByteTimeDomainData(buffer)

      ctx.clearRect(0, 0, c.width, c.height)
      ctx.lineWidth = 2.5
      ctx.strokeStyle = '#ef4444'
      ctx.shadowBlur = 12
      ctx.shadowColor = 'rgba(239,68,68,0.6)'
      ctx.beginPath()
      const slice = c.width / buffer.length
      let x = 0
      for (let i = 0; i < buffer.length; i++) {
        const v = (buffer[i] ?? 128) / 128
        const y = (v * c.height) / 2
        if (i === 0) ctx.moveTo(x, y)
        else ctx.lineTo(x, y)
        x += slice
      }
      ctx.lineTo(c.width, c.height / 2)
      ctx.stroke()
    }
    draw()

    const timer = window.setInterval(() => {
      if (!pausedRef.current) setSeconds((s) => s + 1)
    }, 1000)

    return () => {
      window.clearInterval(timer)
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current)
      try {
        source.disconnect()
      } catch {
        // ignore
      }
      void audioCtx.close().catch(() => undefined)
      // 정리 시엔 '저장하지 않고' 이 녹음기만 종료 (chunks 폐기)
      if (recorder.state !== 'inactive') {
        recorder.onstop = null
        try {
          recorder.stop()
        } catch {
          // ignore
        }
      }
    }
    // stream 단위로만 재생성. onSave/onStop은 functional setState라 stale-safe.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stream])

  const handleStop = () => {
    stopFnRef.current()
  }

  const togglePause = () => {
    const r = recorderRef.current
    if (!r || r.state === 'inactive') return
    const next = !paused
    setPaused(next)
    pausedRef.current = next
    try {
      if (next) r.pause()
      else r.resume()
    } catch {
      // ignore
    }
  }

  return (
    <motion.div
      className="fixed inset-0 z-50 flex items-center justify-center p-6"
      style={{ background: 'rgba(0,0,0,0.55)', backdropFilter: 'blur(14px)' }}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.25 }}
    >
      <motion.div
        className="w-full max-w-sm rounded-3xl border border-white/10 bg-card p-7 shadow-2xl"
        initial={{ scale: 0.92, opacity: 0, y: 12 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.95, opacity: 0 }}
        transition={{ type: 'spring', stiffness: 300, damping: 26 }}
      >
        <div className="flex flex-col items-center gap-6">
          <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
            <motion.span
              className="size-2.5 rounded-full bg-red-500"
              animate={{ opacity: [1, 0.3, 1] }}
              transition={{ duration: 1.2, repeat: Infinity }}
            />
            녹음 중
          </div>

          <p className="text-5xl font-semibold tabular-nums tracking-tight">{formatTime(seconds)}</p>

          <canvas ref={canvasRef} className="h-[140px] w-full rounded-2xl bg-black/40" />

          <div className="flex items-center gap-8">
            <motion.button
              type="button"
              onClick={togglePause}
              whileTap={{ scale: 0.9 }}
              className="flex size-14 items-center justify-center rounded-full bg-secondary text-secondary-foreground"
              aria-label={paused ? '재개' : '일시정지'}
            >
              {paused ? <Play className="size-6" /> : <Pause className="size-6" />}
            </motion.button>
            <motion.button
              type="button"
              onClick={handleStop}
              whileTap={{ scale: 0.9 }}
              whileHover={{ scale: 1.05 }}
              className="flex size-16 items-center justify-center rounded-full bg-red-500 text-white shadow-lg shadow-red-500/30"
              aria-label="정지"
            >
              <Square className="size-6 fill-current" />
            </motion.button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  )
}
